[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "20" }

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"

[install]
  command = "npm install --legacy-peer-deps"

# The following redirects are needed for React Router to work correctly on Netlify.
# All requests that don't match a static file will serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
